ALTER TABLE `gzdata`.`players` 
CHANGE COLUMN `name` `name` VARCHAR(45) NULL ,
CHANGE COLUMN `health` `health` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `sanity` `sanity` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `fighting` `fighting` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `social` `social` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `survival` `survival` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ;
